# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with pnpm pre-installed
FROM node:20-alpine

# Set the working directory
WORKDIR /app

# Install pnpm
RUN npm install -g pnpm@latest

# Copy package.json and pnpm-lock.yaml
COPY package.json pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy the rest of the application code
COPY . .

# Build the application
RUN pnpm build

# Expose necessary ports (if any, adjust as necessary)
EXPOSE 3000

# Set environment variables
ENV NODE_ENV=production
ENV BINANCE_API_KEY=your_api_key_here
ENV BINANCE_API_SECRET=your_secret_key_here

# Run the application
CMD ["pnpm", "start"]